### ISSUE TITLE
GetCVByCosmosAddress must be query, not a transaction 

### ISSUE THREAD

**Issue by AlexS778** [AlexS778/CVProject#6]
GetCVByCosmosAddress is currently a transaction, but it should be a query. 

Solution, create new query in query.proto, generate the code

**Comment by AlexS778** [comment]
```shell
CVProjectd query cvproject get-cv-by-cosmos-address --help
Query getCvByCosmosAddress

Usage:
  CVProjectd query cvproject get-cv-by-cosmos-address [cosmos-address] [flags]
  ```
  
 Actual usage:
 ```
 ➜  CVProject git:(feature/methods) ✗ CVProjectd query cvproject get-cv-by-cosmos-address $alice
cV:
  Companies:
  - comments: Good worker
    companyID: "1"
    companyName: Apple
    creator: cosmos1rr9vhfmlermmrvkkcc9r0k06naj7ua9wnyq4x7
    timestampEnd: "2022-02-22"
    timestampStart: "2022-02-21"
    uuid: "1"
  creator: cosmos1rr9vhfmlermmrvkkcc9r0k06naj7ua9wnyq4x7
  education: MIT
  experience: Executive at Apple
  name: Craig Federighi
  skills: Objective-c
  summary: Engineer
  ```
